--require'bufferline'.setup{}
require'crates'.setup{}
require'litee.calltree'.setup{}
require'litee.filetree'.setup{}
require'litee.lib'.setup{}
require'litee.symboltree'.setup{}
require'neoscroll'.setup{}
require'nvim-autopairs'.setup{}
require'which-key'.setup{}
