qemu-system-x86_64 \
	-name $NAME \
	-nodefaults \
	-enable-kvm \
	-machine q35,type=pc,accel=kvm,vmport=off,kernel_irqchip=on \
	-cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time,kvm=off,hv_vendor_id=1234567890ab \
	-smp cores=6 \
	-m 16G \
	-mem-path /dev/hugepages \
	-device virtio-net,netdev=vmnic \
	-netdev user,id=vmnic \
	-spice port=$SPICE_PORT,disable-ticketing=on \
	-chardev spiceport,id=spagent,name=org.spice-space.webdav.0,debug=0 \
	-chardev spicevmc,id=vdagent,name=vdagent,debug=0 \
	-device vfio-pci,host=29:00.0,x-vga=on,multifunction=on \
	-device vfio-pci,host=29:00.1 \
	-device vfio-pci,host=2a:00.3 \
	-device vfio-pci,host=01:00.0 \
	-device virtio-serial,id=virtio-serial0,max_ports=16 \
	-device virtserialport,chardev=spagent,name=org.spice-space.webdav.0 \
	-device virtserialport,chardev=vdagent,name=com.redhat.spice.0 \
	-chardev socket,id=chrtpm,path=/tmp/emulated_tpm/swtpm-sock \
	-tpmdev emulator,id=tpm0,chardev=chrtpm \
	-device tpm-tis,tpmdev=tpm0 \
	-boot order=cd \
	-bios $OVMF_FD \
	-drive file=/var/Windows11.iso,format=raw,media=cdrom \
	-drive file=/var/virtio-win.iso,format=raw,media=cdrom \
	-nographic \
	-vga none
	# -netdev bridge,id=br0,br=$BRIDGE_INTERFACE \
	# -device virtio-net-pci,netdev=br0 \
